name: learn
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.69.0
  get_storage: ^2.1.1

  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2

flutter_app_name:
  name: "MLearn"

flutter_icons:
  android: "ic_launcher"
  ios: "Icon-App"
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.jpg"

flutter:
    uses-material-design: true
    assets:
      - assets/
      - assets/images/

